import React, { useState, useEffect } from "react";
import { Link, useParams } from "react-router-dom";
import Inings2 from "../components/Inings2";
import Table from "../components/Stats/Table";

const Match = () => {
  const user = JSON.parse(localStorage.getItem("user"));
  

  const matchResponse = {
    "matchId": 3,
    "innings": [
        {
            "inningsId": 19,
            "inningsNumber": 1,
            "battingTeamName": "Pakistan",
            "bowlingTeamName": "West Indies",
            "balls": [
                {
                    "ballId": 514,
                    "overNumber": 1,
                    "ballNumber": 1,
                    "striker": "Babar Azam",
                    "nonStriker": "Fakhar Zaman",
                    "bowler": "Jasprit Bumrah",
                    "runsScored": 5,
                    "wicket": "NONE",
                    "totalScore": 5,
                    "wicketNumber": 0,
                    "inningId": 19
                },
                {
                    "ballId": 515,
                    "overNumber": 1,
                    "ballNumber": 2,
                    "striker": "Fakhar Zaman",
                    "nonStriker": "Babar Azam",
                    "bowler": "Jasprit Bumrah",
                    "runsScored": 3,
                    "wicket": "NONE",
                    "totalScore": 3,
                    "wicketNumber": 0,
                    "inningId": 19
                },
                {
                    "ballId": 516,
                    "overNumber": 1,
                    "ballNumber": 3,
                    "striker": "Babar Azam",
                    "nonStriker": "Fakhar Zaman",
                    "bowler": "Jasprit Bumrah",
                    "runsScored": 3,
                    "wicket": "NONE",
                    "totalScore": 6,
                    "wicketNumber": 0,
                    "inningId": 19
                },
                {
                    "ballId": 517,
                    "overNumber": 1,
                    "ballNumber": 4,
                    "striker": "Fakhar Zaman",
                    "nonStriker": "Babar Azam",
                    "bowler": "Jasprit Bumrah",
                    "runsScored": 3,
                    "wicket": "NONE",
                    "totalScore": 9,
                    "wicketNumber": 0,
                    "inningId": 19
                },
                {
                    "ballId": 518,
                    "overNumber": 1,
                    "ballNumber": 5,
                    "striker": "Babar Azam",
                    "nonStriker": "Fakhar Zaman",
                    "bowler": "Jasprit Bumrah",
                    "runsScored": 0,
                    "wicket": "NONE",
                    "totalScore": 9,
                    "wicketNumber": 0,
                    "inningId": 19
                },
                {
                    "ballId": 519,
                    "overNumber": 1,
                    "ballNumber": 6,
                    "striker": "Babar Azam",
                    "nonStriker": "Fakhar Zaman",
                    "bowler": "Jasprit Bumrah",
                    "runsScored": 2,
                    "wicket": "RUN_OUT",
                    "totalScore": 11,
                    "wicketNumber": 1,
                    "inningId": 19
                },
                {
                    "ballId": 520,
                    "overNumber": 2,
                    "ballNumber": 1,
                    "striker": "Imam-ul-Haq",
                    "nonStriker": "Fakhar Zaman",
                    "bowler": "Mohammed Siraj",
                    "runsScored": 0,
                    "wicket": "NONE",
                    "totalScore": 11,
                    "wicketNumber": 1,
                    "inningId": 19
                },
                {
                    "ballId": 521,
                    "overNumber": 2,
                    "ballNumber": 2,
                    "striker": "Imam-ul-Haq",
                    "nonStriker": "Fakhar Zaman",
                    "bowler": "Mohammed Siraj",
                    "runsScored": 1,
                    "wicket": "NONE",
                    "totalScore": 12,
                    "wicketNumber": 1,
                    "inningId": 19
                },
                {
                    "ballId": 522,
                    "overNumber": 2,
                    "ballNumber": 3,
                    "striker": "Fakhar Zaman",
                    "nonStriker": "Imam-ul-Haq",
                    "bowler": "Mohammed Siraj",
                    "runsScored": 6,
                    "wicket": "NONE",
                    "totalScore": 18,
                    "wicketNumber": 1,
                    "inningId": 19
                },
                {
                    "ballId": 523,
                    "overNumber": 2,
                    "ballNumber": 4,
                    "striker": "Fakhar Zaman",
                    "nonStriker": "Imam-ul-Haq",
                    "bowler": "Mohammed Siraj",
                    "runsScored": 2,
                    "wicket": "NONE",
                    "totalScore": 20,
                    "wicketNumber": 1,
                    "inningId": 19
                },
                {
                    "ballId": 524,
                    "overNumber": 2,
                    "ballNumber": 5,
                    "striker": "Fakhar Zaman",
                    "nonStriker": "Imam-ul-Haq",
                    "bowler": "Mohammed Siraj",
                    "runsScored": 6,
                    "wicket": "RUN_OUT",
                    "totalScore": 26,
                    "wicketNumber": 2,
                    "inningId": 19
                },
                {
                    "ballId": 525,
                    "overNumber": 2,
                    "ballNumber": 6,
                    "striker": "Shoaib Malik",
                    "nonStriker": "Imam-ul-Haq",
                    "bowler": "Mohammed Siraj",
                    "runsScored": 2,
                    "wicket": "NONE",
                    "totalScore": 28,
                    "wicketNumber": 2,
                    "inningId": 19
                },
                {
                    "ballId": 526,
                    "overNumber": 3,
                    "ballNumber": 1,
                    "striker": "Shoaib Malik",
                    "nonStriker": "Imam-ul-Haq",
                    "bowler": "Hardik Pandya",
                    "runsScored": 6,
                    "wicket": "NONE",
                    "totalScore": 34,
                    "wicketNumber": 2,
                    "inningId": 19
                },
                {
                    "ballId": 527,
                    "overNumber": 3,
                    "ballNumber": 2,
                    "striker": "Shoaib Malik",
                    "nonStriker": "Imam-ul-Haq",
                    "bowler": "Hardik Pandya",
                    "runsScored": 2,
                    "wicket": "NONE",
                    "totalScore": 36,
                    "wicketNumber": 2,
                    "inningId": 19
                },
                {
                    "ballId": 528,
                    "overNumber": 3,
                    "ballNumber": 3,
                    "striker": "Shoaib Malik",
                    "nonStriker": "Imam-ul-Haq",
                    "bowler": "Hardik Pandya",
                    "runsScored": 4,
                    "wicket": "NONE",
                    "totalScore": 40,
                    "wicketNumber": 2,
                    "inningId": 19
                },
                {
                    "ballId": 529,
                    "overNumber": 3,
                    "ballNumber": 4,
                    "striker": "Shoaib Malik",
                    "nonStriker": "Imam-ul-Haq",
                    "bowler": "Hardik Pandya",
                    "runsScored": 2,
                    "wicket": "NONE",
                    "totalScore": 42,
                    "wicketNumber": 2,
                    "inningId": 19
                },
                {
                    "ballId": 530,
                    "overNumber": 3,
                    "ballNumber": 5,
                    "striker": "Shoaib Malik",
                    "nonStriker": "Imam-ul-Haq",
                    "bowler": "Hardik Pandya",
                    "runsScored": 1,
                    "wicket": "NONE",
                    "totalScore": 43,
                    "wicketNumber": 2,
                    "inningId": 19
                },
                {
                    "ballId": 531,
                    "overNumber": 3,
                    "ballNumber": 6,
                    "striker": "Imam-ul-Haq",
                    "nonStriker": "Shoaib Malik",
                    "bowler": "Hardik Pandya",
                    "runsScored": 0,
                    "wicket": "NONE",
                    "totalScore": 43,
                    "wicketNumber": 2,
                    "inningId": 19
                },
                {
                    "ballId": 532,
                    "overNumber": 4,
                    "ballNumber": 1,
                    "striker": "Imam-ul-Haq",
                    "nonStriker": "Shoaib Malik",
                    "bowler": "Axar Patel",
                    "runsScored": 5,
                    "wicket": "NONE",
                    "totalScore": 48,
                    "wicketNumber": 2,
                    "inningId": 19
                },
                {
                    "ballId": 533,
                    "overNumber": 4,
                    "ballNumber": 2,
                    "striker": "Shoaib Malik",
                    "nonStriker": "Imam-ul-Haq",
                    "bowler": "Axar Patel",
                    "runsScored": 1,
                    "wicket": "NONE",
                    "totalScore": 49,
                    "wicketNumber": 2,
                    "inningId": 19
                },
                {
                    "ballId": 534,
                    "overNumber": 4,
                    "ballNumber": 3,
                    "striker": "Imam-ul-Haq",
                    "nonStriker": "Shoaib Malik",
                    "bowler": "Axar Patel",
                    "runsScored": 1,
                    "wicket": "NONE",
                    "totalScore": 50,
                    "wicketNumber": 2,
                    "inningId": 19
                },
                {
                    "ballId": 535,
                    "overNumber": 4,
                    "ballNumber": 4,
                    "striker": "Shoaib Malik",
                    "nonStriker": "Imam-ul-Haq",
                    "bowler": "Axar Patel",
                    "runsScored": 4,
                    "wicket": "NONE",
                    "totalScore": 54,
                    "wicketNumber": 2,
                    "inningId": 19
                },
                {
                    "ballId": 536,
                    "overNumber": 4,
                    "ballNumber": 5,
                    "striker": "Shoaib Malik",
                    "nonStriker": "Imam-ul-Haq",
                    "bowler": "Axar Patel",
                    "runsScored": 1,
                    "wicket": "NONE",
                    "totalScore": 55,
                    "wicketNumber": 2,
                    "inningId": 19
                },
                {
                    "ballId": 537,
                    "overNumber": 4,
                    "ballNumber": 6,
                    "striker": "Imam-ul-Haq",
                    "nonStriker": "Shoaib Malik",
                    "bowler": "Axar Patel",
                    "runsScored": 2,
                    "wicket": "NONE",
                    "totalScore": 57,
                    "wicketNumber": 2,
                    "inningId": 19
                },
                {
                    "ballId": 538,
                    "overNumber": 5,
                    "ballNumber": 1,
                    "striker": "Imam-ul-Haq",
                    "nonStriker": "Shoaib Malik",
                    "bowler": "Riyan Parag",
                    "runsScored": 6,
                    "wicket": "NONE",
                    "totalScore": 63,
                    "wicketNumber": 2,
                    "inningId": 19
                },
                {
                    "ballId": 539,
                    "overNumber": 5,
                    "ballNumber": 2,
                    "striker": "Imam-ul-Haq",
                    "nonStriker": "Shoaib Malik",
                    "bowler": "Riyan Parag",
                    "runsScored": 3,
                    "wicket": "NONE",
                    "totalScore": 66,
                    "wicketNumber": 2,
                    "inningId": 19
                },
                {
                    "ballId": 540,
                    "overNumber": 5,
                    "ballNumber": 3,
                    "striker": "Shoaib Malik",
                    "nonStriker": "Imam-ul-Haq",
                    "bowler": "Riyan Parag",
                    "runsScored": 1,
                    "wicket": "NONE",
                    "totalScore": 67,
                    "wicketNumber": 2,
                    "inningId": 19
                },
                {
                    "ballId": 541,
                    "overNumber": 5,
                    "ballNumber": 4,
                    "striker": "Imam-ul-Haq",
                    "nonStriker": "Shoaib Malik",
                    "bowler": "Riyan Parag",
                    "runsScored": 4,
                    "wicket": "NONE",
                    "totalScore": 71,
                    "wicketNumber": 2,
                    "inningId": 19
                },
                {
                    "ballId": 542,
                    "overNumber": 5,
                    "ballNumber": 5,
                    "striker": "Imam-ul-Haq",
                    "nonStriker": "Shoaib Malik",
                    "bowler": "Riyan Parag",
                    "runsScored": 5,
                    "wicket": "NONE",
                    "totalScore": 76,
                    "wicketNumber": 2,
                    "inningId": 19
                },
                {
                    "ballId": 543,
                    "overNumber": 5,
                    "ballNumber": 6,
                    "striker": "Shoaib Malik",
                    "nonStriker": "Imam-ul-Haq",
                    "bowler": "Riyan Parag",
                    "runsScored": 4,
                    "wicket": "NONE",
                    "totalScore": 80,
                    "wicketNumber": 2,
                    "inningId": 19
                },
                {
                    "ballId": 544,
                    "overNumber": 6,
                    "ballNumber": 1,
                    "striker": "Shoaib Malik",
                    "nonStriker": "Imam-ul-Haq",
                    "bowler": "Bhuvneshwar Kumar",
                    "runsScored": 2,
                    "wicket": "NONE",
                    "totalScore": 82,
                    "wicketNumber": 2,
                    "inningId": 19
                },
                {
                    "ballId": 545,
                    "overNumber": 6,
                    "ballNumber": 2,
                    "striker": "Shoaib Malik",
                    "nonStriker": "Imam-ul-Haq",
                    "bowler": "Bhuvneshwar Kumar",
                    "runsScored": 5,
                    "wicket": "NONE",
                    "totalScore": 87,
                    "wicketNumber": 2,
                    "inningId": 19
                },
                {
                    "ballId": 546,
                    "overNumber": 6,
                    "ballNumber": 3,
                    "striker": "Imam-ul-Haq",
                    "nonStriker": "Shoaib Malik",
                    "bowler": "Bhuvneshwar Kumar",
                    "runsScored": 0,
                    "wicket": "HIT_WICKET",
                    "totalScore": 87,
                    "wicketNumber": 3,
                    "inningId": 19
                },
                {
                    "ballId": 547,
                    "overNumber": 6,
                    "ballNumber": 4,
                    "striker": "Mohammad Rizwan",
                    "nonStriker": "Shoaib Malik",
                    "bowler": "Bhuvneshwar Kumar",
                    "runsScored": 6,
                    "wicket": "NONE",
                    "totalScore": 93,
                    "wicketNumber": 3,
                    "inningId": 19
                },
                {
                    "ballId": 548,
                    "overNumber": 6,
                    "ballNumber": 5,
                    "striker": "Mohammad Rizwan",
                    "nonStriker": "Shoaib Malik",
                    "bowler": "Bhuvneshwar Kumar",
                    "runsScored": 4,
                    "wicket": "NONE",
                    "totalScore": 97,
                    "wicketNumber": 3,
                    "inningId": 19
                },
                {
                    "ballId": 549,
                    "overNumber": 6,
                    "ballNumber": 6,
                    "striker": "Mohammad Rizwan",
                    "nonStriker": "Shoaib Malik",
                    "bowler": "Bhuvneshwar Kumar",
                    "runsScored": 5,
                    "wicket": "NONE",
                    "totalScore": 102,
                    "wicketNumber": 3,
                    "inningId": 19
                },
                {
                    "ballId": 550,
                    "overNumber": 7,
                    "ballNumber": 1,
                    "striker": "Shoaib Malik",
                    "nonStriker": "Mohammad Rizwan",
                    "bowler": "Shardul Thakur",
                    "runsScored": 5,
                    "wicket": "NONE",
                    "totalScore": 107,
                    "wicketNumber": 3,
                    "inningId": 19
                },
                {
                    "ballId": 551,
                    "overNumber": 7,
                    "ballNumber": 2,
                    "striker": "Mohammad Rizwan",
                    "nonStriker": "Shoaib Malik",
                    "bowler": "Shardul Thakur",
                    "runsScored": 4,
                    "wicket": "HIT_WICKET",
                    "totalScore": 111,
                    "wicketNumber": 4,
                    "inningId": 19
                },
                {
                    "ballId": 552,
                    "overNumber": 7,
                    "ballNumber": 3,
                    "striker": "Mohammad Nawaz",
                    "nonStriker": "Shoaib Malik",
                    "bowler": "Shardul Thakur",
                    "runsScored": 5,
                    "wicket": "NONE",
                    "totalScore": 116,
                    "wicketNumber": 4,
                    "inningId": 19
                },
                {
                    "ballId": 553,
                    "overNumber": 7,
                    "ballNumber": 4,
                    "striker": "Shoaib Malik",
                    "nonStriker": "Mohammad Nawaz",
                    "bowler": "Shardul Thakur",
                    "runsScored": 2,
                    "wicket": "NONE",
                    "totalScore": 118,
                    "wicketNumber": 4,
                    "inningId": 19
                },
                {
                    "ballId": 554,
                    "overNumber": 7,
                    "ballNumber": 5,
                    "striker": "Shoaib Malik",
                    "nonStriker": "Mohammad Nawaz",
                    "bowler": "Shardul Thakur",
                    "runsScored": 0,
                    "wicket": "NONE",
                    "totalScore": 118,
                    "wicketNumber": 4,
                    "inningId": 19
                },
                {
                    "ballId": 555,
                    "overNumber": 7,
                    "ballNumber": 6,
                    "striker": "Shoaib Malik",
                    "nonStriker": "Mohammad Nawaz",
                    "bowler": "Shardul Thakur",
                    "runsScored": 2,
                    "wicket": "NONE",
                    "totalScore": 120,
                    "wicketNumber": 4,
                    "inningId": 19
                }
            ]
        },
        {
            "inningsId": 20,
            "inningsNumber": 2,
            "battingTeamName": "West Indies",
            "bowlingTeamName": "Pakistan",
            "balls": [
                {
                    "ballId": 556,
                    "overNumber": 1,
                    "ballNumber": 1,
                    "striker": "Virat Kohli",
                    "nonStriker": "Rohit Sharma",
                    "bowler": "Shaheen Afridi",
                    "runsScored": 6,
                    "wicket": "CAUGHT_ON_BOWLED",
                    "totalScore": 6,
                    "wicketNumber": 1,
                    "inningId": 20
                },
                {
                    "ballId": 557,
                    "overNumber": 1,
                    "ballNumber": 2,
                    "striker": "Shubman Gill",
                    "nonStriker": "Rohit Sharma",
                    "bowler": "Shaheen Afridi",
                    "runsScored": 1,
                    "wicket": "NONE",
                    "totalScore": 1,
                    "wicketNumber": 1,
                    "inningId": 20
                },
                {
                    "ballId": 558,
                    "overNumber": 1,
                    "ballNumber": 3,
                    "striker": "Rohit Sharma",
                    "nonStriker": "Shubman Gill",
                    "bowler": "Shaheen Afridi",
                    "runsScored": 4,
                    "wicket": "NONE",
                    "totalScore": 5,
                    "wicketNumber": 1,
                    "inningId": 20
                },
                {
                    "ballId": 559,
                    "overNumber": 1,
                    "ballNumber": 4,
                    "striker": "Rohit Sharma",
                    "nonStriker": "Shubman Gill",
                    "bowler": "Shaheen Afridi",
                    "runsScored": 1,
                    "wicket": "NONE",
                    "totalScore": 6,
                    "wicketNumber": 1,
                    "inningId": 20
                },
                {
                    "ballId": 560,
                    "overNumber": 1,
                    "ballNumber": 5,
                    "striker": "Shubman Gill",
                    "nonStriker": "Rohit Sharma",
                    "bowler": "Shaheen Afridi",
                    "runsScored": 4,
                    "wicket": "NONE",
                    "totalScore": 10,
                    "wicketNumber": 1,
                    "inningId": 20
                },
                {
                    "ballId": 561,
                    "overNumber": 1,
                    "ballNumber": 6,
                    "striker": "Shubman Gill",
                    "nonStriker": "Rohit Sharma",
                    "bowler": "Shaheen Afridi",
                    "runsScored": 5,
                    "wicket": "NONE",
                    "totalScore": 15,
                    "wicketNumber": 1,
                    "inningId": 20
                },
                {
                    "ballId": 562,
                    "overNumber": 2,
                    "ballNumber": 1,
                    "striker": "Rohit Sharma",
                    "nonStriker": "Shubman Gill",
                    "bowler": "Shahnawaz Dahani",
                    "runsScored": 3,
                    "wicket": "NONE",
                    "totalScore": 18,
                    "wicketNumber": 1,
                    "inningId": 20
                },
                {
                    "ballId": 563,
                    "overNumber": 2,
                    "ballNumber": 2,
                    "striker": "Shubman Gill",
                    "nonStriker": "Rohit Sharma",
                    "bowler": "Shahnawaz Dahani",
                    "runsScored": 6,
                    "wicket": "NONE",
                    "totalScore": 24,
                    "wicketNumber": 1,
                    "inningId": 20
                },
                {
                    "ballId": 564,
                    "overNumber": 2,
                    "ballNumber": 3,
                    "striker": "Shubman Gill",
                    "nonStriker": "Rohit Sharma",
                    "bowler": "Shahnawaz Dahani",
                    "runsScored": 0,
                    "wicket": "NONE",
                    "totalScore": 24,
                    "wicketNumber": 1,
                    "inningId": 20
                },
                {
                    "ballId": 565,
                    "overNumber": 2,
                    "ballNumber": 4,
                    "striker": "Shubman Gill",
                    "nonStriker": "Rohit Sharma",
                    "bowler": "Shahnawaz Dahani",
                    "runsScored": 4,
                    "wicket": "NONE",
                    "totalScore": 28,
                    "wicketNumber": 1,
                    "inningId": 20
                },
                {
                    "ballId": 566,
                    "overNumber": 2,
                    "ballNumber": 5,
                    "striker": "Shubman Gill",
                    "nonStriker": "Rohit Sharma",
                    "bowler": "Shahnawaz Dahani",
                    "runsScored": 3,
                    "wicket": "NONE",
                    "totalScore": 31,
                    "wicketNumber": 1,
                    "inningId": 20
                },
                {
                    "ballId": 567,
                    "overNumber": 2,
                    "ballNumber": 6,
                    "striker": "Rohit Sharma",
                    "nonStriker": "Shubman Gill",
                    "bowler": "Shahnawaz Dahani",
                    "runsScored": 1,
                    "wicket": "NONE",
                    "totalScore": 32,
                    "wicketNumber": 1,
                    "inningId": 20
                },
                {
                    "ballId": 568,
                    "overNumber": 3,
                    "ballNumber": 1,
                    "striker": "Shubman Gill",
                    "nonStriker": "Rohit Sharma",
                    "bowler": "Mohammad Nawaz",
                    "runsScored": 1,
                    "wicket": "NONE",
                    "totalScore": 33,
                    "wicketNumber": 1,
                    "inningId": 20
                },
                {
                    "ballId": 569,
                    "overNumber": 3,
                    "ballNumber": 2,
                    "striker": "Rohit Sharma",
                    "nonStriker": "Shubman Gill",
                    "bowler": "Mohammad Nawaz",
                    "runsScored": 5,
                    "wicket": "NONE",
                    "totalScore": 38,
                    "wicketNumber": 1,
                    "inningId": 20
                },
                {
                    "ballId": 570,
                    "overNumber": 3,
                    "ballNumber": 3,
                    "striker": "Shubman Gill",
                    "nonStriker": "Rohit Sharma",
                    "bowler": "Mohammad Nawaz",
                    "runsScored": 1,
                    "wicket": "NONE",
                    "totalScore": 39,
                    "wicketNumber": 1,
                    "inningId": 20
                },
                {
                    "ballId": 571,
                    "overNumber": 3,
                    "ballNumber": 4,
                    "striker": "Rohit Sharma",
                    "nonStriker": "Shubman Gill",
                    "bowler": "Mohammad Nawaz",
                    "runsScored": 1,
                    "wicket": "NONE",
                    "totalScore": 40,
                    "wicketNumber": 1,
                    "inningId": 20
                },
                {
                    "ballId": 572,
                    "overNumber": 3,
                    "ballNumber": 5,
                    "striker": "Shubman Gill",
                    "nonStriker": "Rohit Sharma",
                    "bowler": "Mohammad Nawaz",
                    "runsScored": 5,
                    "wicket": "NONE",
                    "totalScore": 45,
                    "wicketNumber": 1,
                    "inningId": 20
                },
                {
                    "ballId": 573,
                    "overNumber": 3,
                    "ballNumber": 6,
                    "striker": "Rohit Sharma",
                    "nonStriker": "Shubman Gill",
                    "bowler": "Mohammad Nawaz",
                    "runsScored": 0,
                    "wicket": "HIT_WICKET",
                    "totalScore": 45,
                    "wicketNumber": 2,
                    "inningId": 20
                },
                {
                    "ballId": 574,
                    "overNumber": 4,
                    "ballNumber": 1,
                    "striker": "KL Rahul",
                    "nonStriker": "Shubman Gill",
                    "bowler": "Imad Wasim",
                    "runsScored": 1,
                    "wicket": "NONE",
                    "totalScore": 46,
                    "wicketNumber": 2,
                    "inningId": 20
                },
                {
                    "ballId": 575,
                    "overNumber": 4,
                    "ballNumber": 2,
                    "striker": "Shubman Gill",
                    "nonStriker": "KL Rahul",
                    "bowler": "Imad Wasim",
                    "runsScored": 1,
                    "wicket": "NONE",
                    "totalScore": 47,
                    "wicketNumber": 2,
                    "inningId": 20
                },
                {
                    "ballId": 576,
                    "overNumber": 4,
                    "ballNumber": 3,
                    "striker": "KL Rahul",
                    "nonStriker": "Shubman Gill",
                    "bowler": "Imad Wasim",
                    "runsScored": 1,
                    "wicket": "NONE",
                    "totalScore": 48,
                    "wicketNumber": 2,
                    "inningId": 20
                },
                {
                    "ballId": 577,
                    "overNumber": 4,
                    "ballNumber": 4,
                    "striker": "Shubman Gill",
                    "nonStriker": "KL Rahul",
                    "bowler": "Imad Wasim",
                    "runsScored": 6,
                    "wicket": "NONE",
                    "totalScore": 54,
                    "wicketNumber": 2,
                    "inningId": 20
                },
                {
                    "ballId": 578,
                    "overNumber": 4,
                    "ballNumber": 5,
                    "striker": "Shubman Gill",
                    "nonStriker": "KL Rahul",
                    "bowler": "Imad Wasim",
                    "runsScored": 1,
                    "wicket": "NONE",
                    "totalScore": 55,
                    "wicketNumber": 2,
                    "inningId": 20
                },
                {
                    "ballId": 579,
                    "overNumber": 4,
                    "ballNumber": 6,
                    "striker": "KL Rahul",
                    "nonStriker": "Shubman Gill",
                    "bowler": "Imad Wasim",
                    "runsScored": 0,
                    "wicket": "NONE",
                    "totalScore": 55,
                    "wicketNumber": 2,
                    "inningId": 20
                },
                {
                    "ballId": 580,
                    "overNumber": 5,
                    "ballNumber": 1,
                    "striker": "KL Rahul",
                    "nonStriker": "Shubman Gill",
                    "bowler": "Mohammad Hafeez",
                    "runsScored": 4,
                    "wicket": "NONE",
                    "totalScore": 59,
                    "wicketNumber": 2,
                    "inningId": 20
                },
                {
                    "ballId": 581,
                    "overNumber": 5,
                    "ballNumber": 2,
                    "striker": "KL Rahul",
                    "nonStriker": "Shubman Gill",
                    "bowler": "Mohammad Hafeez",
                    "runsScored": 1,
                    "wicket": "NONE",
                    "totalScore": 60,
                    "wicketNumber": 2,
                    "inningId": 20
                },
                {
                    "ballId": 582,
                    "overNumber": 5,
                    "ballNumber": 3,
                    "striker": "Shubman Gill",
                    "nonStriker": "KL Rahul",
                    "bowler": "Mohammad Hafeez",
                    "runsScored": 1,
                    "wicket": "NONE",
                    "totalScore": 61,
                    "wicketNumber": 2,
                    "inningId": 20
                },
                {
                    "ballId": 583,
                    "overNumber": 5,
                    "ballNumber": 4,
                    "striker": "KL Rahul",
                    "nonStriker": "Shubman Gill",
                    "bowler": "Mohammad Hafeez",
                    "runsScored": 6,
                    "wicket": "NONE",
                    "totalScore": 67,
                    "wicketNumber": 2,
                    "inningId": 20
                },
                {
                    "ballId": 584,
                    "overNumber": 5,
                    "ballNumber": 5,
                    "striker": "KL Rahul",
                    "nonStriker": "Shubman Gill",
                    "bowler": "Mohammad Hafeez",
                    "runsScored": 4,
                    "wicket": "NONE",
                    "totalScore": 71,
                    "wicketNumber": 2,
                    "inningId": 20
                },
                {
                    "ballId": 585,
                    "overNumber": 5,
                    "ballNumber": 6,
                    "striker": "KL Rahul",
                    "nonStriker": "Shubman Gill",
                    "bowler": "Mohammad Hafeez",
                    "runsScored": 1,
                    "wicket": "NONE",
                    "totalScore": 72,
                    "wicketNumber": 2,
                    "inningId": 20
                },
                {
                    "ballId": 586,
                    "overNumber": 6,
                    "ballNumber": 1,
                    "striker": "Shubman Gill",
                    "nonStriker": "KL Rahul",
                    "bowler": "Mohammad Wasim Jr.",
                    "runsScored": 0,
                    "wicket": "NONE",
                    "totalScore": 72,
                    "wicketNumber": 2,
                    "inningId": 20
                },
                {
                    "ballId": 587,
                    "overNumber": 6,
                    "ballNumber": 2,
                    "striker": "Shubman Gill",
                    "nonStriker": "KL Rahul",
                    "bowler": "Mohammad Wasim Jr.",
                    "runsScored": 4,
                    "wicket": "NONE",
                    "totalScore": 76,
                    "wicketNumber": 2,
                    "inningId": 20
                },
                {
                    "ballId": 588,
                    "overNumber": 6,
                    "ballNumber": 3,
                    "striker": "Shubman Gill",
                    "nonStriker": "KL Rahul",
                    "bowler": "Mohammad Wasim Jr.",
                    "runsScored": 2,
                    "wicket": "NONE",
                    "totalScore": 78,
                    "wicketNumber": 2,
                    "inningId": 20
                },
                {
                    "ballId": 589,
                    "overNumber": 6,
                    "ballNumber": 4,
                    "striker": "Shubman Gill",
                    "nonStriker": "KL Rahul",
                    "bowler": "Mohammad Wasim Jr.",
                    "runsScored": 4,
                    "wicket": "NONE",
                    "totalScore": 82,
                    "wicketNumber": 2,
                    "inningId": 20
                },
                {
                    "ballId": 590,
                    "overNumber": 6,
                    "ballNumber": 5,
                    "striker": "Shubman Gill",
                    "nonStriker": "KL Rahul",
                    "bowler": "Mohammad Wasim Jr.",
                    "runsScored": 1,
                    "wicket": "NONE",
                    "totalScore": 83,
                    "wicketNumber": 2,
                    "inningId": 20
                },
                {
                    "ballId": 591,
                    "overNumber": 6,
                    "ballNumber": 6,
                    "striker": "KL Rahul",
                    "nonStriker": "Shubman Gill",
                    "bowler": "Mohammad Wasim Jr.",
                    "runsScored": 5,
                    "wicket": "NONE",
                    "totalScore": 88,
                    "wicketNumber": 2,
                    "inningId": 20
                },
                {
                    "ballId": 592,
                    "overNumber": 7,
                    "ballNumber": 1,
                    "striker": "Shubman Gill",
                    "nonStriker": "KL Rahul",
                    "bowler": "Haris Rauf",
                    "runsScored": 3,
                    "wicket": "NONE",
                    "totalScore": 91,
                    "wicketNumber": 2,
                    "inningId": 20
                },
                {
                    "ballId": 593,
                    "overNumber": 7,
                    "ballNumber": 2,
                    "striker": "KL Rahul",
                    "nonStriker": "Shubman Gill",
                    "bowler": "Haris Rauf",
                    "runsScored": 3,
                    "wicket": "NONE",
                    "totalScore": 94,
                    "wicketNumber": 2,
                    "inningId": 20
                },
                {
                    "ballId": 594,
                    "overNumber": 7,
                    "ballNumber": 3,
                    "striker": "Shubman Gill",
                    "nonStriker": "KL Rahul",
                    "bowler": "Haris Rauf",
                    "runsScored": 0,
                    "wicket": "NONE",
                    "totalScore": 94,
                    "wicketNumber": 2,
                    "inningId": 20
                },
                {
                    "ballId": 595,
                    "overNumber": 7,
                    "ballNumber": 4,
                    "striker": "Shubman Gill",
                    "nonStriker": "KL Rahul",
                    "bowler": "Haris Rauf",
                    "runsScored": 6,
                    "wicket": "NONE",
                    "totalScore": 100,
                    "wicketNumber": 2,
                    "inningId": 20
                },
                {
                    "ballId": 596,
                    "overNumber": 7,
                    "ballNumber": 5,
                    "striker": "Shubman Gill",
                    "nonStriker": "KL Rahul",
                    "bowler": "Haris Rauf",
                    "runsScored": 2,
                    "wicket": "NONE",
                    "totalScore": 102,
                    "wicketNumber": 2,
                    "inningId": 20
                },
                {
                    "ballId": 597,
                    "overNumber": 7,
                    "ballNumber": 6,
                    "striker": "Shubman Gill",
                    "nonStriker": "KL Rahul",
                    "bowler": "Haris Rauf",
                    "runsScored": 1,
                    "wicket": "NONE",
                    "totalScore": 103,
                    "wicketNumber": 2,
                    "inningId": 20
                }
            ]
        }
    ]
}

  const { id } = useParams();

  return (
    <div className="rounded-[10px] w-[100%] bg-black h-[100%] p-[2rem] flex flex-col gap-[1rem] relative">
      <div
        className={`w-[100%] h-[100%] flex flex-col items-center gap-[1rem] overflow-y-hidden`}
      >
        <div className="w-[100%] h-[15%] flex justify-between gap-[1rem] mt-[0.5rem] ">
          <div className="w-[60%] h-[100%] flex flex-col">
            <span className="text-white text-[32px] font-bold truncate ">
             
              <span className="text-[#34e8eb]">Australia</span>  VS <span className="text-[#bff23d]">India</span> 
            </span>
            <span className="font-light text-white">
              {"ICC T20 World Cup"}
            </span>
            <span className="font-light text-white fon">
              {"(PLAYOFFS)"}
            </span>
          </div>

          <div className="w-[20%] h-[100%] font-extralight text-white flex flex-col justify-end items-end">
            <button className="border w-[7rem] py-[0.5rem]">Start</button>
          </div>
        </div>

        <div className="w-[100%] h-[0.3rem] bg-[#434343] rounded-[10px]"></div>
        <div className="w-[20%] h-[6%] rounded-[10px] bg-[#434343] text-white font-bold flex items-center justify-around gap-[1rem]">
          <button className={`text-[#FF730D]`}>Inings</button>

          <button className={`  `}>Score card</button>
        </div>
        <Inings2 innings={matchResponse.innings}/>
      </div>
    </div>
  );
};

export default Match;
